### ISSUE TITLE
[Task] 캘린더에 작성일자가 마크되는 기능 구현

### ISSUE THREAD

**Issue by Leekyeongmi** [codestates/siphoon-note#104]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`
- Type: `feature`

### TODO
1. [x] 달력 라이브러리 리서치
2. [x] 페이지에 맞게 달력 CSS 커스터마이징
3. [x] 작성일자 배열을 받아서 특정 날짜를 마크하는 기능 구현
