### ISSUE TITLE
[Task] 메인페이지(회원용) 메세지 입력창 제작

### ISSUE THREAD

**Issue by ghost** [codestates/siphoon-note#12]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`, `Advanced`, `Nightmare`
- Type: `bug`, `feature`, `delete`

### TODO
1. [x] 메시지 입력창은 화면의 1/3 그리드 레이아웃 설정
2. [x] 입력창 만들기
3. [x] 글 남기기 버튼 만들기
4. [x] 타이머/입력창 리셋 버튼 만들기
5. [x] 매세지 입력창이 유효하지 않은 텍스트(빈텍스트) 경우 남기기 버튼 클릭 비활성화 기능
