### ISSUE TITLE
[Task] 메시지 입력창 타이머 기능 구현 (advanced)

### ISSUE THREAD

**Issue by ghost** [codestates/siphoon-note#15]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`, `Advanced`, `Nightmare`
- Type: `bug`, `feature`, `delete`

### TODO
1. [ ] 글 남기기 버튼 클릭시 10분이 되지 않아도, 서버에 요청하기
2. [ ] 입력을 시작하면, 타이머가 자동으로 시작되고 타이머가 종료되면 post 요청 보내기
3. [x] 타이머/입력창 리셋 버튼 클릭 시, 기능 구현하기
