### ISSUE TITLE
[Task]  로고 제작하기

### ISSUE THREAD

**Issue by ghost** [codestates/siphoon-note#19]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`, `Advanced`, `Nightmare`
- Type: `bug`, `feature`, `delete`

### TODO
1. [x] 로고 리서치 하기 (vs 타이포)
~~2. [ ] 클릭 시, 랜딩페이지로 리디렉션~~ 
3. [x] 마우스 호버시 애니메이션 적용
4. [x] 스크롤 다운이 되어도 상단에 고정
~~5. [ ] 마우스 커서 모양 변경~~
6. [x] 서비스명 반영해서 타이포로 제작하기
