### ISSUE TITLE
[Task] 서비스 소개 화면 제작(advanced)

### ISSUE THREAD

**Issue by ghost** [codestates/siphoon-note#21]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`, `Advanced`, `Nightmare`
- Type: `bug`, `feature`, `delete`

### TODO
1. [x] 소개 내용(글) 제외한 윤곽 잡기
2. [x] 가로너비 화면을 채우면서 내려오는 소개컷 만들기
3. [x] 상단으로 올라가기 버튼과 기능 만들기
4. [x] 아래 화살표 클릭시 스무스한 화면 전환
5. [x] 스크롤 트리거 에니메이션 구현
