### ISSUE TITLE
[Task] 404 에러 페이지 제작

### ISSUE THREAD

**Issue by jongyeol12** [codestates/siphoon-note#23]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`, `Advanced`, `Nightmare`
- Type: `bug`, `feature`, `delete`

### TODO
1. [x] 에러 페이지 제작
2. [x] 유저가 잘못된 접근 시, 에러 페이지로 리디렉션
3. [x] 뒤로가기 버튼/기능 만들기
