### ISSUE TITLE
[Task] 메세지 출력창 제작(advanced)

### ISSUE THREAD

**Issue by ghost** [codestates/siphoon-note#24]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`, `Advanced`, `Nightmare`
- Type: `bug`, `feature`, `delete`

### TODO
1. [x] 마우스 호버 시, 삭제 아이콘과 날짜 보이는 애니메이션 적용
2. [ ] 삭제 버튼 클릭 시, 모달창으로 확인하기
3. [ ] 서버에 삭제 요청하기
4. [ ] 무한 스크롤 기능
5. [ ] 위로 올라가기 버튼
