### ISSUE TITLE
[Task] 랜딩페이지 랭킹, 공개글 페이지 제작 

### ISSUE THREAD

**Issue by ghost** [codestates/siphoon-note#25]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`
- Type: `feature`

### TODO
1. [x] 랭킹 레이아웃 제작
2. [x] 공개글 레이아웃 제작
3. [x] 공개글 캐러셀 슬라이드 기능 구현
4. [x] 글 클릭 시 더보기 컴포넌트 불러오기
