### ISSUE TITLE
[Task] 검색 필터링 기능 구현(advanced)

### ISSUE THREAD

**Issue by ghost** [codestates/siphoon-note#27]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`, `Advanced`, `Nightmare`
- Type: `bug`, `feature`, `delete`

### TODO
1. [x] 검색창 만들기
2. [x] 필터링 해제 x 박스 만들기
3. [ ] 서버에서 받아온 메세지 필터링 기능 
4. [ ] x 버튼 클릭 시, 필터링 해제하기 기능
