### ISSUE TITLE
[CM/Task] 프로젝트 기획 및 초기 환경 세팅

### ISSUE THREAD

**Issue by ghost** [codestates/siphoon-note#3]
### ISSUE
- Group:  `sr`
- Type: `add`
- Detail: add sr, wiki

### TODO
- [x] SR 기획 작성
- [x] Wiki 작성
  - [x] 프로젝트 소개 페이지 (home)
  - [x] API 문서 페이지
  - [x] DB Schema 페이지
  - [x] Requirements 페이지
  - [x] Team Rule 페이지
  - [x] Wireframe 페이지
  - [x] flow Chart 페이지 
- [x] Issue Template 추가
- [x] Issue Label 추가

### Labels
- Estimated time: `E: 3h+`
- Group : `Common`
- Sprint: `Sprint`
- Urgency: `Middle`
