### ISSUE TITLE
[Task]  client 초기세팅

### ISSUE THREAD

**Issue by ghost** [codestates/siphoon-note#4]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`, `Advanced`, `Nightmare`
- Type: `bug`, `feature`, `delete`

### TODO
1. [x] Create React App 실행
2. [x] eslint, prettier 설정하기
3. [x] 필요 모듈 설치(axios, react ... 등)
