### ISSUE TITLE
[Task] 네비게이션 컴포넌트 만들기

### ISSUE THREAD

**Issue by ghost** [codestates/siphoon-note#6]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`, `Advanced`, `Nightmare`
- Type: `bug`, `feature`, `delete`

### TODO
1. [x] 로그인 버튼 만들고 로그인 컴포넌트로 Link
2. [x] 회원가입 버튼 만들고 회원가입 컴포넌트로 Link
3. [x] 스크롤 다운이 되어도 상단에 고정
