### ISSUE TITLE
[Task] (로그인 상태의) 네비게이션 컴포넌트 만들기 

### ISSUE THREAD

**Issue by ghost** [codestates/siphoon-note#7]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`, `Advanced`, `Nightmare`
- Type: `bug`, `feature`, `delete`

### TODO
1. [x] 로그인 상태인 경우, 위의 버튼은 사라지고 회원정보가 나타나게 렌더링 (회원정보 사진 아이콘)
2. [x] 회원정보 수정과 로그아웃을 위한 드롭다운 제작
3. [x] 회원정보 수정 버튼 클릭 시, 수정 컴포넌트로 Link
4. [ ] 로그아웃 버튼 클릭 시, 서버 요청 보내고 랜딩페이지로 리디렉션
