### ISSUE TITLE
[Task] 서비스 소개 화면 제작

### ISSUE THREAD

**Issue by ghost** [codestates/siphoon-note#8]
### ISSUE
- Group:  `client`
- Priority: `Bare-Minimun`, `Advanced`, `Nightmare`
- Type: `bug`, `feature`, `delete`

### TODO
1. [x] 웹사이트의 첫인상인 이미지추가 (배경에 들어갈 요소들 + 메인)
2. [x] 시작하기 버튼 만들기
3. [x] 버튼 클릭 시, 로그인 상태에 따라 다른 메인 페이지로 이동
